### PR TITLE
Fixed #12

### LINKED ISSUE #12: Add option to keep qualifiers in simplifyClaims()
After `simplifyClaims()`, all qualifiers are discarded. This makes it impossible for e.g. merging P50 (author) and P2093 (author string) after fetching labels, as the P1545 (series ordinal) qualifier is gone. It would be nice to to have an option for `simplifyClaims()` or a similar method to keep these.

### PR DESCRIPTION
**Pull request by larsgw**
It should fix #12 and I fixed the test cases to accommodate the API change. Compiling with coffee 1.12.2 instead of 1.11.1, which makes most of the changes. Perhaps the API change should be optional, but that's not for me to decide. I haven't updated the docs yet.

### CODE REVIEW

**Comment by larsgw** [comment]
I overlooked some things with the qualifiers. I'll fix them as fast as possible:

- [x] `qualifiers` is not a part of `mainsnak` but part of `claim`
- [ ] `qualifiers` seems to be different from normal claim collections, which is harder to fix

**Comment by maxlath** [comment]
Thanks for the PR!
To make things simpler (hopefully), I have finally [got into the long awaited task of converting the project from coffeescript to javascript](https://github.com/maxlath/wikidata-sdk/tree/decoffeeifying) \o/
Could you do your changes from this new version and update this PR? Please don't commit the build files, I do that before releasing to make it easy to get started with using the lib, but they should not pollute the list of file changes the rest of the time.

On the PR's content, from what I saw, I would prefer not breaking the current interface, and only get the qualifiers if a given option is passed, what do you think?

**Comment by larsgw** [comment]
I changed it to work like this:
```javascript
wdk.simplifyClaims(entity.claims, null, null, true)
wdk.simplifyPropertyClaims(entity.claims.P50, null, null, true)
wdk.simplifyClaim(entity.claims.P50[0], null, null, true)
```

**Comment by maxlath** [comment]
thanks! I merged and made a few corrections:
* added tests 988a641
* formatted a few things to my taste ;) c86f692
* fixed an issue with in your implementation: it wasn't including property prefixes in qualifiers claims 7c3e5fc (see tests)

**Comment by larsgw** [comment]
Note: I only found the commenting-code-inline button when it was too late.

The tests seem good although [`for...in` shouldn't be used for arrays](http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-a-bad-idea). It's better to use `for...of`, and if you want indices use the following (see [this](http://stackoverflow.com/a/34349737)):
```js
for (let [index, value] of array.entries()) {
  // ...
}
```
Formatting is entirely you choice, of course. Line-by-line:

```
```

- [`40`](https://github.com/maxlath/wikidata-sdk/commit/c86f692a63280ec3db813d51c71cb7b70face76f#diff-28d0238ffb3e414c6d6fc63807d822a2R40): Not my prefered style, but it's not my code :)

```js
   const simpleQualifiers = {}
```

- [`71`](https://github.com/maxlath/wikidata-sdk/commit/c86f692a63280ec3db813d51c71cb7b70face76f#diff-28d0238ffb3e414c6d6fc63807d822a2R71): I used `let` because the properties would change, but I forgot that that didn't matter

```js
     .slice()
     .map(simplifyQualifierClaim)
```

- [`78`](https://github.com/maxlath/wikidata-sdk/commit/c86f692a63280ec3db813d51c71cb7b70face76f#diff-28d0238ffb3e414c6d6fc63807d822a2R78): I did the whitespace the same way you used [here](https://github.com/maxlath/wikidata-sdk/blob/c86f692a63280ec3db813d51c71cb7b70face76f/lib/helpers/simplify_claims.js#L21-L22)
```js
   const simplifyQualifierClaim = function (claim) {
     return simplifyClaim({ mainsnak: claim }, entityPrefix, propertyPrefix)
   }
```
and
```js
     .map(simplifyQualifierClaim)
```
- [`79`](https://github.com/maxlath/wikidata-sdk/commit/c86f692a63280ec3db813d51c71cb7b70face76f#diff-28d0238ffb3e414c6d6fc63807d822a2R72): You used inline arrow-functions [here](https://github.com/maxlath/wikidata-sdk/blob/c86f692a63280ec3db813d51c71cb7b70face76f/lib/helpers/simplify_claims.js#L21), so I thought it would be okay

Concerning the implementation issue: I changed from calling `simplifyClaims()` to `simplifyClaim()` because you need to loop over the properties anyway, and I forgot the prefix.

**Comment by maxlath** [comment]
I tend to write
```js
return bar
.slice()
.map(buzz)
```
but add indentation when the result of the chain is assigned to some variable
```js
var foo = bar
  .slice()
  .map(buzz)
```
I find it clearer, but some might find it inconsistent I guess ^^

**Comment by maxlath** [comment]
@larsgw I just released 4.2.0, thank you for your contribution \o/

**Pull request merged**
