### PR TITLE
Fix crash on simplifyresults, when itemLabel field is null.

### PR DESCRIPTION
**Pull request by jacquarg**
Hi Maxlath,
Thank for this lib, which help me in a new upcomming MesInfos app ; )

Sorry, it's an old fix, it's then more an issue than a PR, but I didn't manage to make the actual master of wikidata-sdk work.

But the bug is still their in the current master, and not located very far.

### CODE REVIEW

**Comment by maxlath** [comment]
hello \o/
could you give a concrete case where this issue arise?

**Comment by jacquarg** [comment]
This method, with 'Q8954081' as dataId :
```
function getMovieData(wikidataId) {
  const sparql = `SELECT ?label ?wikiLink ?originalTitle ?composer ?composerLabel
      ?genre ?genreLabel ?publicationDate ?duration ?director ?directorLabel
      ?musicBrainzRGId ?imdbId ?countryOfOrigin ?countryOfOriginLabel
    WHERE {
     wd:${wikidataId} wdt:P31/wdt:P279* wd:Q11424;
    rdfs:label ?label.
    OPTIONAL { wd:${wikidataId} wdt:P1476 ?originalTitle. }
    OPTIONAL { wd:${wikidataId} wdt:P86 ?composer. }
    OPTIONAL { wd:${wikidataId} wdt:P136 ?genre. }
    OPTIONAL { wd:${wikidataId} wdt:P495 ?countryOfOrigin. }
    OPTIONAL { wd:${wikidataId} wdt:P577 ?publicationDate. }
    OPTIONAL { wd:${wikidataId} wdt:P2047 ?duration. }
    OPTIONAL { wd:${wikidataId} wdt:P57 ?director. }
    OPTIONAL { wd:${wikidataId} wdt:P436 ?musicBrainzRGId. }
    OPTIONAL { wd:${wikidataId} wdt:P345 ?imdbId. }
    OPTIONAL {
      ?wikiLink schema:about wd:${wikidataId}.
      ?wikiLink schema:inLanguage "fr".
      FILTER (SUBSTR(str(?wikiLink), 1, 25) = "https://fr.wikipedia.org/")
    }

    SERVICE wikibase:label { bd:serviceParam wikibase:language "fr" . }

    filter langMatches(lang(?label),'fr')
  }
  LIMIT 1`;

  return $.getJSON(wdk.sparqlQuery(sparql))
  .then(wdk.simplifySparqlResults)
  .then((movies) => {
    movies[0].wikidataId = wikidataId;
    return movies[0];
  });
};

```

**Comment by maxlath** [comment]
@jacquarg could you confirm that 8ea47e5 fixes it before I make a release?

**Comment by jacquarg** [comment]
@maxlath 
Looks good to me, and it works now.

Thanks !!

FYI: package.json's scripts doesn't work with node 4.5.0 / npm 2.15.9 ; but work great with node 6.9.4 / npm 3.10.10 .

**Comment by maxlath** [comment]
which scripts fails on 4.5.0?

**Comment by maxlath** [comment]
release 4.2.4 published!

**Comment by jacquarg** [comment]
It's in the test. May be some ES6 feature not handled correctly by 4.5 ?

This is the end of the trace:

```
> wikidata-sdk@4.2.3 test /home/jacquarg/workspace/wikidata-sdk
> mocha

/home/jacquarg/workspace/wikidata-sdk/test/general.js:7
    const { parse, helpers } = wdk
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/jacquarg/workspace/wikidata-sdk/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/jacquarg/workspace/wikidata-sdk/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/jacquarg/workspace/wikidata-sdk/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/home/jacquarg/workspace/wikidata-sdk/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
npm ERR! Test failed.  See above for more details.
done prepublishing...

```

**Comment by maxlath** [comment]
indeed! [Destructuring assignment arrived in v6](http://node.green/#destructuring--assignment)

**Pull request closed without merging**
